CREATE DATABASE DDWEBAPP;
USE DDWEBAPP;

CREATE TABLE IF NOT EXISTS ACCOUNT (
userID INT PRIMARY KEY AUTO_INCREMENT,
userEmail VARCHAR(65) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS DATADICTIONARY (
dictionaryID INT PRIMARY KEY AUTO_INCREMENT,
userEmail VARCHAR(65) NOT NULL,
title VARCHAR(65) NOT NULL,
created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
versionNo VARCHAR(10) NOT NULL,

CONSTRAINT FOREIGN KEY (userEmail)
REFERENCES ACCOUNT (userEmail)
);

CREATE TABLE IF NOT EXISTS DDTABLE (
tableName VARCHAR(65) NOT NULL,
dictionaryID INT NOT NULL,

PRIMARY KEY (tableName, dictionaryID),

CONSTRAINT FOREIGN KEY (dictionaryID)
REFERENCES DATADICTIONARY (dictionaryID)
ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ATTRIBUTE (
attributeName VARCHAR(40) NOT NULL,
tableName VARCHAR(65) NOT NULL,
dictionaryID INT NOT NULL,
attributeKey VARCHAR(20),
attributeType VARCHAR(25),
attributeSize VARCHAR(10),
attributeConstraints VARCHAR(100),
attributeRef VARCHAR(100),
attributeDesc VARCHAR(200),

PRIMARY KEY (attributeName, tableName, dictionaryID),

CONSTRAINT FOREIGN KEY (tableName)
REFERENCES DDTABLE (tableName)
ON DELETE CASCADE,

CONSTRAINT FOREIGN KEY (dictionaryID)
REFERENCES DATADICTIONARY (dictionaryID)
ON DELETE CASCADE
);
