CREATE DATABASE DDWEBAPP;
USE DDWEBAPP;

CREATE TABLE IF NOT EXISTS ACCOUNT (
userID INT PRIMARY KEY AUTO_INCREMENT,
emailAddress VARCHAR(65) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS DATADICTIONARY (
dictionaryID INT PRIMARY KEY AUTO_INCREMENT,
title VARCHAR(65) NOT NULL,
created DATETIME NOT NULL,
versionNo VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS DDTABLE (
tableName VARCHAR(65) NOT NULL,
dictionaryID INT NOT NULL,

PRIMARY KEY (tableName, dictionaryID),

CONSTRAINT FOREIGN KEY (dictionaryID)
REFERENCES DATADICTIONARY (dictionaryID)
);

CREATE TABLE IF NOT EXISTS ATTRIBUTE (
attributeName VARCHAR(40) NOT NULL,
tableName VARCHAR(65) NOT NULL,
dictionaryID INT NOT NULL,
attributeKey VARCHAR(20),
attributeType VARCHAR(25),
attributeSize VARCHAR(10),
attributeConstraints VARCHAR(100),
attributeRef VARCHAR(100),
attributeDesc VARCHAR(200),

PRIMARY KEY (attributeName, tableName, dictionaryID),

CONSTRAINT FOREIGN KEY (tableName)
REFERENCES DDTABLE (tableName),

CONSTRAINT FOREIGN KEY (dictionaryID)
REFERENCES DATADICTIONARY (dictionaryID)
);
